# Kong API Gateway 配置
# 用于开发、staging 和生产环境

services:
  # Kong 数据库 (PostgreSQL) - 用于存储 Kong 配置
  kong-db:
    image: postgres:18
    restart: always
    networks:
      - kong-network
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD:-kong}
      POSTGRES_DB: kong
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kong 数据库迁移
  kong-migrations:
    image: kong:3.4
    restart: on-failure
    networks:
      - kong-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kong}
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap
    depends_on:
      kong-db:
        condition: service_healthy

  # Kong Gateway
  kong:
    image: kong:3.4
    restart: always
    networks:
      - kong-network
      - default
    environment:
      # 数据库配置
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kong}
      KONG_PG_DATABASE: kong

      # Kong 配置
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001

      # 插件配置
      KONG_PLUGINS: bundled

      # 信任所有 IP（用于 Docker 环境）
      KONG_TRUSTED_IPS: 0.0.0.0/0,::/0

      # 日志级别
      KONG_LOG_LEVEL: info
    ports:
      - "8000:8000"   # Kong 代理端口 (HTTP)
      - "8443:8443"   # Kong 代理端口 (HTTPS)
      - "8001:8001"   # Kong Admin API (内部访问)
      - "8444:8444"   # Kong Admin API (HTTPS, 内部访问)
    depends_on:
      kong-db:
        condition: service_healthy
      kong-migrations:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Konga - Kong 的开源管理界面
  konga:
    image: pantsel/konga:latest
    restart: always
    networks:
      - kong-network
      - default
    environment:
      NODE_ENV: production
      KONGA_HOOK_TIMEOUT: 120000
    ports:
      - "1337:1337"
    depends_on:
      - kong

volumes:
  kong-db-data:

networks:
  kong-network:
    name: ${STACK_NAME:-full-stack-fastapi-project}_kong
    external: false
  default:
    external: true
    name: ${STACK_NAME:-full-stack-fastapi-project}_default
