// This file is auto-generated by @hey-api/openapi-ts

export type Body_files_upload_file = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BusinessUnitCreate = {
    name: string;
    code: string;
    description?: (string | null);
    is_active?: boolean;
};

export type BusinessUnitPublic = {
    name: string;
    code: string;
    description?: (string | null);
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
};

export type BusinessUnitsPublic = {
    data: Array<BusinessUnitPublic>;
    count: number;
};

export type BusinessUnitUpdate = {
    name?: (string | null);
    code?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type FilePublic = {
    filename: string;
    original_filename: string;
    content_type: string;
    file_size: number;
    responsible_function_id?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type FilesPublic = {
    data: Array<FilePublic>;
    count: number;
};

export type FunctionCreate = {
    name: string;
    code: string;
    description?: (string | null);
    is_active?: boolean;
    business_unit_id: string;
};

export type FunctionPublic = {
    name: string;
    code: string;
    description?: (string | null);
    is_active?: boolean;
    business_unit_id: string;
    id: string;
    created_at?: (string | null);
};

export type FunctionsPublic = {
    data: Array<FunctionPublic>;
    count: number;
};

export type FunctionUpdate = {
    name?: (string | null);
    code?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    business_unit_id?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    business_unit_id?: (string | null);
    function_id?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    business_unit_id?: (string | null);
    function_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    business_unit_id?: (string | null);
    function_id?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type BusinessUnitsReadBusinessUnitsData = {
    limit?: number;
    skip?: number;
};

export type BusinessUnitsReadBusinessUnitsResponse = (BusinessUnitsPublic);

export type BusinessUnitsCreateBusinessUnitData = {
    requestBody: BusinessUnitCreate;
};

export type BusinessUnitsCreateBusinessUnitResponse = (BusinessUnitPublic);

export type BusinessUnitsReadBusinessUnitData = {
    buId: string;
};

export type BusinessUnitsReadBusinessUnitResponse = (BusinessUnitPublic);

export type BusinessUnitsUpdateBusinessUnitData = {
    buId: string;
    requestBody: BusinessUnitUpdate;
};

export type BusinessUnitsUpdateBusinessUnitResponse = (BusinessUnitPublic);

export type BusinessUnitsDeleteBusinessUnitData = {
    buId: string;
};

export type BusinessUnitsDeleteBusinessUnitResponse = (Message);

export type FilesReadFilesData = {
    limit?: number;
    skip?: number;
};

export type FilesReadFilesResponse = (FilesPublic);

export type FilesReadFileData = {
    id: string;
};

export type FilesReadFileResponse = (FilePublic);

export type FilesDeleteFileEndpointData = {
    id: string;
};

export type FilesDeleteFileEndpointResponse = (Message);

export type FilesUploadFileData = {
    formData: Body_files_upload_file;
    /**
     * Function that uploaded this file
     */
    responsibleFunctionId?: (string | null);
    /**
     * BU that can view this file
     */
    visibleBuId?: (string | null);
    /**
     * Comma-separated function IDs that can view this file
     */
    visibleFunctionIds?: (string | null);
};

export type FilesUploadFileResponse = (FilePublic);

export type FilesDownloadFileData = {
    id: string;
};

export type FilesDownloadFileResponse = (unknown);

export type FilesGetFileUrlData = {
    expiresIn?: number;
    id: string;
};

export type FilesGetFileUrlResponse = (unknown);

export type FunctionsReadFunctionsData = {
    /**
     * Filter by business unit
     */
    businessUnitId?: (string | null);
    limit?: number;
    skip?: number;
};

export type FunctionsReadFunctionsResponse = (FunctionsPublic);

export type FunctionsCreateFunctionData = {
    requestBody: FunctionCreate;
};

export type FunctionsCreateFunctionResponse = (FunctionPublic);

export type FunctionsReadFunctionData = {
    funcId: string;
};

export type FunctionsReadFunctionResponse = (FunctionPublic);

export type FunctionsUpdateFunctionData = {
    funcId: string;
    requestBody: FunctionUpdate;
};

export type FunctionsUpdateFunctionResponse = (FunctionPublic);

export type FunctionsDeleteFunctionData = {
    funcId: string;
};

export type FunctionsDeleteFunctionResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);